### ISSUE TITLE
私のREADME.mdをコピペしましたね！？！？？！

### ISSUE THREAD

**Issue by naoido** [dokkiitech/dokkiitech#1]
## 問題の概要

私のプロジェクトの `README.md` を **ほぼコピペ** しているリポジトリを発見しました。この行為は著作権や倫理的な観点から問題がある可能性があります。

## 問題の詳細

- **該当リポジトリ**: [該当リポジトリ](https://github.com/dokkiitech/dokkiitech)
- **該当箇所**: `README.md`
- **確認日時**: 2024/12/8 1:23

以下のような点で問題があると考えられます。

## 問題点

1. **著作権の侵害**
   - 私が作成した `README.md` は明らかに独自の内容です。
   - ほぼコピペされた内容がそのまま利用されています。

2. **クレジットの欠如**
   - `README.md` におけるクレジットやオリジナルのリンクが記載されていません。

3. **プロジェクトの信頼性への影響**
   - 他のプロジェクトで無断利用されると、私のプロジェクトの信頼性が損なわれる可能性があります。

## 提案する解決策

以下の対応をお願いいたします：

1. **適切なクレジットの記載**  
   `README.md` の冒頭に、私のプロジェクトへのリンクとクレジットを明記してください。

## 参考情報

- **オリジナルのリポジトリ**: [オリジナルリポジトリ](https://github.com/naoido/naoido)
- **オリジナル作成日**: 2024/11/29

---

ご確認のうえ、早急にご対応いただけますようお願いいたします。

**Comment by naoido** [comment]
@dokkiitech

**Comment by naoido** [comment]
@dokkiitech

**Comment by naoido** [comment]
@dokkiitech 💢

**Comment by naoido** [comment]
@dokkiitech 👀👀

**Comment by dokkiitech** [comment]
@naoido 
ご提案いただきありがとうございました🙃
愛してます❤️
